# Site Build Settings



# Build settings
permalink:           none
plugins:             [jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "UltrawideSnowboards.com"
description:	       "A website dedicated to tracking all the ultrawide snowboards"
author:                "SRLM"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
